apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bonita
  name: bonita
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bonita
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: bonita
    spec:
      containers:
        - command:
            - bash
            - -c
            - |
              set -e
              echo 'Waiting for Postgres to be available'
              export PGPASSWORD="$POSTGRES_ENV_POSTGRES_PASSWORD"
              maxTries=10
              while [ "$maxTries" -gt 0 ] && ! psql -h "$DB_HOST" -U 'postgres' -c '\l'; do
                  let maxTries--
                  sleep 1
              done
              echo
              if [ "$maxTries" -le 0 ]; then
                  echo >&2 'error: unable to contact Postgres after 10 tries'
                  exit 1
              fi
              exec /opt/files/startup.sh
          env:
            - name: DB_HOST
              value: db
            - name: DB_VENDOR
              value: postgres
            - name: PLATFORM_LOGIN
              value: pfadmin
            - name: PLATFORM_PASSWORD
              value: pfsecret
            - name: POSTGRES_ENV_POSTGRES_PASSWORD
              value: example
            - name: TENANT_LOGIN
              value: tech_user
            - name: TENANT_PASSWORD
              value: secret
          image: bonita
          name: bonita
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
